### ISSUE TITLE
Unable to render the notebook.

### ISSUE THREAD

**Issue by SherylHYX** [tdurieux/anonymous_github#65] opened 2021-08-08 06:00 UTC
Hello developers,

I have a repo with several jupyter notebooks to show. I can show some of them but not the others. Typically, the notebooks that fail to be shown are updated these three days. Surprisingly, I just put one test notebook with two cells on and it could be shown. The other notebooks, even with larger sizes than the current notebooks, can be shown without a problem. Could you help? Thanks!

Best,
Yixuan He (Sheryl)

**Comment by tdurieux** [comment] 2021-08-13 05:15
That is strange maybe it is due to anonymization. do you have an error in the console of the browser?
Can you send me the link to your repository by email?

**Comment by tdurieux** [comment] 2021-08-13 08:38
The problem is related to the order of the libraries. It is fixed in production. The fix will be included in the next release.

**Closed** 2021-08-13 08:39 UTC
Labels: bug
