### ISSUE TITLE
Cloning from anonymous github

### ISSUE THREAD

**Issue by suyash67** [tdurieux/anonymous_github#24] opened 2019-08-31 19:25 UTC
How do we clone a repository from anonymous github? Please help me out.

**Comment by tdurieux** [comment] 2019-09-01 05:53
it is not possible, sorry.

**Comment by TheShadow29** [comment] 2019-11-21 01:58
@tdurieux Thank you for the amazing work.

Wondering if is there any interest in supporting cloning from an anonymous repository? One use case is where we want to upload our code in a zip format after anonymization.

**Comment by tdurieux** [comment] 2019-11-21 03:00
I m considering it but it would require a complete reimplementation of the service. I need time  and I don’t have a lot :/

**Comment by ShoufaChen** [comment] 2019-11-25 01:43
hello, @TheShadow29, @tdurieux .

I have finished a simple project to download the repository from anonymous4open.
https://github.com/ShoufaChen/clone-anonymous4open

This implementation is not very elegant now but works properly. Hope it will be helpful.

**Comment by real-or-random** [comment] 2020-01-20 10:04
> @tdurieux Thank you for the amazing work.
> 
> Wondering if is there any interest in supporting cloning from an anonymous repository? One use case is where we want to upload our code in a zip format after anonymization.

Do you mean "download" instead of "upload"? This would really be a useful thing. For now, a simple workaround is to add a zip file to the repo itself for submission. But this won't have the "XXX" feature of course.

**Comment by gwern** [comment] 2020-11-17 17:50
If you are unable to provide any kind of git clone or archive download due to lack of time, please at least don't go out of your way to detect and block downloading entirely!

~~~
 $ wget -m 'https://anonymous.4open.science/r/5c1049ba-109f-4a12-9d74-9a4a5130ce97/'
--2020-11-17 12:46:23--  https://anonymous.4open.science/r/5c1049ba-109f-4a12-9d74-9a4a5130ce97/
Resolving anonymous.4open.science (anonymous.4open.science)... 104.31.90.163, 172.67.183.76, 104.31.91.163, ...
Connecting to anonymous.4open.science (anonymous.4open.science)|104.31.90.163|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2020-11-17 12:46:23 ERROR 403: Forbidden.
~~~

**Comment by tdurieux** [comment] 2020-11-17 17:53
I did nothing about that.

**Comment by gwern** [comment] 2020-11-17 18:01
It is your server blocking requests, and even if you did not explicitly enable it, that does users no good. How exactly are we supposed to use the anonymous repos to do any kind of peer review or test things out when there is no download functionality and your server blocks the usual last resorts of crawling/scraping? I did not expect to have to fight DRM and pull out my old notes on cookies and HTTP headers just to download a repo.

**Comment by tdurieux** [comment] 2020-11-17 18:08
This is not the usage of this service. It is meant to be a service to visualize the anonymized GitHub repo not to download it. 
I am sorry that you would like other features but with the current implementation, it is not possible for several technical reasons. 

Feel free to create your own anonymize service, pay and maintain it for a year. I would be happy to use it.

**Comment by gwern** [comment] 2020-11-17 18:42
I wouldn't because anonymized peer review is deeply flawed and has been repeatedly experimentally shown to be highly unreliable and largely useless compared to much better methodologies like pre-registered reports (and that's without adding in silliness like blocking downloads and making excuses for it).

For everyone else, the best approach I have found so far is using https://github.com/ShoufaChen/clone-anonymous4open to download repos and bypass the web interface. It has some bugs which I've filed fixes on (specifically, too-large files & spaces in filenames).

**Comment by monperrus** [comment] 2020-11-17 20:25
> It is your server blocking requests,

No, the server does not block anything. But maybe Cloudflare does so.

> https://github.com/ShoufaChen/clone-anonymous4open

Interesting, thanks for sharing.

> How exactly are we supposed to use the anonymous repos to do any kind of peer review 

I'd suggest to ask your PC chair about a better solution.

**Comment by johentsch** [comment] 2020-11-18 12:39
> It is your server blocking requests, and even if you did not explicitly enable it, that does users no good. How exactly are we supposed to use the anonymous repos to do any kind of peer review or test things out when there is no download functionality and your server blocks the usual last resorts of crawling/scraping? I did not expect to have to fight DRM and pull out my old notes on cookies and HTTP headers just to download a repo.

The reproachful tone is out of place in thr context of open source where developers give away work they did in their free time. If you have to blind review the repo, ask the editor to provide the anonymized data as a ZIP because you require it to properly review and that's that.

**Comment by gwern** [comment] 2020-11-18 15:17
A reproachful tone is perfectly appropriate when dealing with a maintainer whose response to a serious bug is to deflect and give the most narrowly technically-correct (surely the best possible way of being correct...) answer of "I did nothing about that", without investigating what the problem is, which does nothing to solve this problem and serves only to deflect blame onto the (many) users who are having this problem of being unable to download repos, as you also are doing in your comment by coming up with reasons for everyone but anonymous_github to do things to work around its problems.

**Comment by johentsch** [comment] 2020-11-18 15:55
You can be angry at anyone you want. It won't necessarily convince anyone to help you. Personally, I wouldn't move a finger for someone sporting such a tone when they are actually the one who wants something.

**Comment by gwern** [comment] 2020-11-18 16:08
Further user-blaming and tone-policing to shift the blame to anyone but oneself. The bug remains.

**Comment by davidgabriel42** [comment] 2021-03-16 21:17
This is still an issue. Would appreciate workaround if not solution. I'm having difficulty downloading large files even without clone tools using web interface. I think this is somewhat in conflict with the mission of open reproducibility.

**Comment by tdurieux** [comment] 2021-03-17 07:23
Once the paper is published the paper will contain the GitHub link. The open reproducibility is therefore not impacted. 
I agree that it would be nice to be able to download the anonymized repository, unfortunately it would not be sustainable for me. It would increase drastically the cost of the service. I put a donation button recently as an experiment to see if donation could cover the cost of this feature but I did not receive any donation. Since I m not ready to spend more of my personal money, this feature will unfortunately not be available.

**Comment by kumavis** [comment] 2021-05-23 09:06
can you imagine judging a cooking contest by only reading the ingredients? 😋 

the `anonymous_github` idea initially seems useful but without the ability to access a copy of the code, its less useful than just distributing a zip. you should put a disclaimer indicating that reviewers will not be able to download the code

thanks for your consideration

**Comment by tdurieux** [comment] 2021-05-23 09:36
Like I said in the issue, it is just a question of money this service already costs me overall $2000. I am not willing to spend more money per month on this service. 
Adding, this feature will increase the storage and compute required. Do a donation of $250 and you will sponsor this feature for a year. I will be happy to support it but not financially. 

It is not just streaming the zip from GitHub... You need to anonymize it and there are GitHub API rate limit therefore I have to cache everything. It is not a problem for small repositories but for repositories that have gigabyte of data it is. Those repositories are more frequent than you think.

Also, it is clearly written in the FAQ that the repos are not downloadable.

**Comment by vanpyre** [comment] 2021-05-29 21:14
Hi @tdurieux. Thank you for this great JOB!

I really appreciate your effort in maintaining this project and I totally agree with you regarding the behavior of @gwern.

I read all the documentation and FAQ to make sure I fully understand the purpose of the project.

I'm not sure if I was looking for it right, but I didn't find any licenses in the documentation. maybe including a GNU LINCENSE is a good idea to avoid some dissatisfactions from some comrades.

To be honest, it would be great have this feature, but i understand all the issues to implement it.

Best regards

**Comment by tdurieux** [comment] 2021-05-30 15:36
Thanks @vanpyre.

> I'm not sure if I was looking for it right, but I didn't find any licenses in the documentation. Maybe including a GNU LINCENSE is a good idea to avoid some dissatisfactions from some comrades.

Thanks for the reminder I forgot about it. I was planning to using MIT, but GNU is probably a better option. I will do that right now.

> To be honest, it would be great have this feature, but i understand all the issues to implement it.

Implementing the feature is relatively easy, 2-3h my issue is really what would be the impact of this feature. I will probably implement it soon but I will not activate the feature if someone wants to deploy a new instance it would be available. I really hope that some conferences could deploy their instance.

**Comment by Matheus-Garbelini** [comment] 2021-06-09 09:16
Hi, adding a zip file shows "The file type is not supported. Anonymous GitHub cannot handle it."
Is there some work around to this?

**Comment by tdurieux** [comment] 2021-06-09 09:20
Zip is a binary, I cannot anonymize it. I am not sure what I can do.

**Comment by daeh** [comment] 2022-02-10 17:52
This is such a useful service. Thank you for developing it. I do think that the ability to clone anonymized repositories is the only critical feature missing. If it's a resources issue, I wonder if one of the large conferences that uses double-blind review (e.g. CogSci) would be up for funding it. Have you talked to organizations about sponsoring this fantastic project?

**Comment by agb94** [comment] 2022-05-01 05:25
https://github.com/agb94/download-anonymous-github
This is the code that I used to clone repositories from Anonymous GitHub.
Some papers contain the Anonymous GitHub link even in the camera-ready version, so I needed to develop it. I hope this will be useful for someone who wants to download the repo.

**Comment by kynehc** [comment] 2022-06-02 12:58
> https://github.com/agb94/download-anonymous-github This is the code that I used to clone repositories from Anonymous GitHub. Some papers contain the Anonymous GitHub link even in the camera-ready version, so I needed to develop it. I hope this will be useful for someone who wants to download the repo.

This is another option with concurrent download from me: https://github.com/kynehc/clone_anonymous_github

**Comment by jiang-yuan** [comment] 2022-06-08 10:45
> 

Thank you. Easy to use.

**Comment by jiang-yuan** [comment] 2022-06-08 10:45
> https://github.com/agb94/download-anonymous-github This is the code that I used to clone repositories from Anonymous GitHub. Some papers contain the Anonymous GitHub link even in the camera-ready version, so I needed to develop it. I hope this will be useful for someone who wants to download the repo.

Thank you. Easy to use.

**Comment by server-python** [comment] 2022-08-10 03:22
Check out my new virus il :)
I made it with C# :)
https://github.com/server-python/-
این ویروس رو تو هر سروری ـآپلود کنید سرور میره هواD:

**Comment by tdurieux** [comment] 2022-10-04 11:56
It is now possible to download repositories that are smaller than 150kb. You will find a button o the top right of the page.

**Comment by 12f23eddde** [comment] 2022-10-06 06:37
It's totally possible to download a repository as a zip archive with the api, and I've created a simple python script to do this: https://gist.github.com/12f23eddde/afaf4f6af4608f42b3721cef5e26260a
Guess downloading and compression can be done in the browser with libraries like [zip.js](https://github.com/gildas-lormeau/zip.js)?

**Comment by tdurieux** [comment] 2022-10-06 06:40
Possible but this costs me a lot, thus using your script will put the website finance (my pocket money) in trouble.
Don't abuse otherwise I will need to take measures...

**Comment by alexandertornede** [comment] 2022-10-18 06:20
@tdurieux You wrote above that it is now possible to download repositories of up to 150kb. Does that mean the feature is in general implemented and can be activated also for larger repositories, if we deploy the service on our own server?

Also: Thanks a lot for implementing :).

**Comment by tdurieux** [comment] 2022-10-18 07:34
Yes, it is. In fact, it is implemented for a year now, but I only added the button recently. 
If you want to deploy your own instance, it is relatively easy. 
1. Clone the repo
2. create a .env in the root folder with
```
GITHUB_TOKEN=
CLIENT_ID=                   # github app client id
CLIENT_SECRET=         # github app secret
AUTH_CALLBACK=https://<your_doamin>/github/auth
PORT=5000
DB_USERNAME=          # choose a db username
DB_PASSWORD=         # choose a db password
STORAGE=filesystem
NODE_ENV=production
NODE_DEBUG=bull
TURST_PROXY=3
RATE_LIMIT=350
MAX_FILE_SIZE=                                   # in byte
MAX_REPO_SIZE=                                 # in kb
AUTO_DOWNLOAD_REPO_SIZE=        # in kb
FREE_DOWNLOAD_REPO_SIZE=         # in kb
```
3. `docker-compose up -d`

**Comment by Maximvdw** [comment] 2023-02-06 12:29
> This is not the usage of this service. It is meant to be a service to visualize the anonymized GitHub repo not to download it. I am sorry that you would like other features but with the current implementation, it is not possible for several technical reasons.
> 
> Feel free to create your own anonymize service, pay and maintain it for a year. I would be happy to use it.

Use case: I agree that this is not the goal of anonymous_github. My reasoning would be that some papers require the uploading of supplemental material as well. In order to make sure that the anonymisation does not differ from the online source, a download would be nice. Also, while I trust the uptime of your hosted version :), as an author you may want to offer as many alternatives as possible for your reviewers.

Possible idea: to support this use case, the download of a tarball (without compression) could be a feature that is only for owners of the repo (on-demand). Maybe somewhere under "actions". It is less resource intensive than a zip file and limiting it to owners would also limit bandwidth. In addition, you can also limit that downloading a tarball is only for repositories in 'download' mode.

**Comment by tdurieux** [comment] 2023-02-06 15:04
The latest version of Anonymous GitHub operates on AWS object storage, not on a file system. As a result, the process of anonymizing a repository involves several steps:

1. Extraction of files from the repository
2. Storage of the extracted files in AWS object storage
3. Downloading and anonymizing the stored files
4. Compression of the anonymized files into a zip file

This process is resource-intensive and may take a long time to complete. 

For your usage, I created a `cli` interface for anonymous GitHub. You can now use it locally:

```bash
# Install the Anonymous GitHub CLI tool
npm install -g @tdurieux/anonymous_github

# Run the Anonymous GitHub CLI tool
anonymous_github
```

**Comment by gy2256** [comment] 2023-10-05 06:47
I used this to clone the repo: [https://github.com/fedebotu/clone-anonymous-github](https://github.com/fedebotu/clone-anonymous-github)

**Comment by tdurieux** [comment] 2023-10-05 07:45
> Possible idea: to support this use case, the download of a tarball could be a feature that is only for owners of the repo (on-demand). Maybe somewhere under "actions". It is less resource intensive than a zip file and limiting it to owners would also limit bandwidth. In addition, you can also limit that downloading a tarball is only for repositories in 'download' mode.

It is something that I considered (#66). I need to find time and resources. I apply for a funding this month last hope, I got selected.

**Comment by tdurieux** [comment] 2024-05-07 17:09
Clone is not supported but, download is now supported for all repositories. I consider this issue as resolved. I hope you enjoy this new feature.

**Comment by kynehc** [comment] 2024-05-07 17:09
Auto Reply test

**Closed** 2024-05-07 17:19 UTC
Labels: enhancement

**Comment by monperrus** [comment] 2024-05-08 04:51
thanks @tdurieux

**Comment by thibmonsel** [comment] 2024-05-13 17:22
@tdurieux thanks for the great work, I was wondering if we should let the repository uploader choose if he accepts that his anonymized repository be downloaded by adding a check box instead of having on the website ? 
```
/!\ Download Repository Feature is now available for all repositories! 
```

**Comment by tdurieux** [comment] 2024-05-13 17:26
Unfortunately not, check #289
