### ISSUE TITLE
The link I used in publication no longer works

### ISSUE THREAD

**Issue by dbogatov** [tdurieux/anonymous_github#27] opened 2019-10-23 17:30 UTC
Hi,

I have used the service to anonymize my public repo for double-blind conference.
Now I discover that the link no longer works.
This is devastating since people are currently reviewing the paper and this code is the strongest contribution!

The repo https://github.com/IBM/dac-lib
The anonymized link is https://anonymous.4open.science/r/1335dc45-3197-4d98-87b9-6478edea78d0/

I am asking, as soon as possible, to recreate the object with **this same link**.
So that the reviewers can access the code.

**Comment by dbogatov** [comment] 2019-10-23 17:34
I see that the website just go new look.
It seems that all the mappings were lost when during the upgrade.
Anyway, it should not be too hard to recreate this particular one.

**Comment by tdurieux** [comment] 2019-10-23 19:00
Normally, nothing should be lost. I pay attention to that.
I will look what is happening.

**Comment by tdurieux** [comment] 2019-10-23 19:09
I look at it, the issue is related to a too important number of request to GitHub.
It should be fixed in a few minutes.

Sorry about that

**Comment by dbogatov** [comment] 2019-10-23 19:24
No problem, thank you for the prompt response!
Let me know when to check the link again

**Comment by tdurieux** [comment] 2019-10-23 19:40
It is working again :)

**Comment by dbogatov** [comment] 2019-10-23 19:41
Oh, thank you so much!

Out of curiosity what was it?

**Comment by tdurieux** [comment] 2019-10-23 19:43
I think just GitHub rate limit on my account.

I am doing research using GitHub data, I am doing a lot of requests to GitHub. I did not realize that I could impact the service :/ 

I will be careful now.

**Closed** 2019-10-23 19:47 UTC
